name: "DJANGO_CTF"

services:
  postgres:
    image: postgres:17
    container_name: postgres_ctf
    environment:
      POSTGRES_DB: ${DJANGO_CTF_POSTGRESQL_NAME}
      POSTGRES_USER: ${DJANGO_CTF_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${DJANGO_CTF_POSTGRESQL_PASSWORD}
    restart: always
    volumes:
      - ./for_docker/postgres_data:/var/lib/postgresql/data
    profiles:
      - prod
      - dev
    networks:
      - lambda_search

  django:
    build: .
    container_name: django_ctf
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./for_docker/static:/DJANGO_CTF/static
      - ./for_docker/media:/DJANGO_CTF/media
      - ./for_docker/logs:/DJANGO_CTF/logs
    depends_on:
      - postgres
    profiles:
      - prod
      - dev
    networks:
      - lambda_search

networks:
  lambda_search:
    external: true