name: "Django_CTF"

services:
  postgres:
    image: postgres:17
    container_name: postgres_ctf
    environment:
      POSTGRES_DB: ${DJANG_CTF_POSTGRESQL_NAME}
      POSTGRES_USER: ${DJANGO_CTF_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${DJANGO_CTF_POSTGRESQL_PASSWORD}
    restart: always
    volumes:
      - ./for_docker/postgres_data:/var/lib/postgresql/data
    profiles:
      - prod
      - dev

  django:
    build: .
    container_name: django_ctf
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./for_docker/static:/Django_CTF/static
      - ./for_docker/media:/Django_CTF/media
      - ./for_docker/logs:/Django_CTF/logs
    depends_on:
      - postgres
    profiles:
      - prod
      - dev

  nginx-prod:
    image: jonasal/nginx-certbot:latest
    container_name: nginx-prod_ctf
    environment:
      DEBUG: ${CTF_CERTBOT_DEBUG}
      STAGING: ${CTF_CERTBOT_STAGING}
      CERTBOT_EMAIL: ${CTF_CERTBOT_EMAIL}
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./for_docker/nginx-confs/Django_CTF_prod.conf:/etc/nginx/user_conf.d/Django_CTF.conf
      - ./for_docker/nginx_certificates:/etc/letsencrypt
      - ./for_docker/static:/Django_CTF/static
      - ./for_docker/media:/Django_CTF/media
    depends_on:
      - django
    profiles:
      - prod

networks:
  default:
    driver: bridge
